language: python
python:
  - 3.4
virtualenv:
  system_site_package: true
before_install:
  - sudo apt-get update
  - sudo apt-get install -qq python-numpy python-matplotlib python-scipy
  - pip install -r requirements.txt --use-mirrors
script:
  - tests/runtests.sh
notifications:
  email:
    - eg@gaute.vetsj.com

