language: python

python:
  # This is not actually used. Because it would take an overly long time
  # to build scipy we cannot use the virtual env of travis. Instead, we
  # use miniconda.
  - 2.7
  - 3.3
  - 3.4

sudo: false

cache:
  directories:
    - ibcao_download

install:
  # Install miniconda
  # -----------------
  - if [[ "$TRAVIS_PYTHON_VERSION" == 2* ]]; then
      wget http://repo.continuum.io/miniconda/Miniconda-3.7.0-Linux-x86_64.sh -O miniconda.sh;
    else
      wget http://repo.continuum.io/miniconda/Miniconda3-3.7.0-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"

  # Create the basic testing environment
  # ------------------------------------
  - conda config --set always_yes yes --set changeps1 no --set show_channel_urls yes
  - conda update conda
  - conda create -n test-environment python=$TRAVIS_PYTHON_VERSION
  - source activate test-environment

  # Customise the testing environment
  # ---------------------------------
  - conda config --add channels scitools
  - conda install matplotlib
  - conda install scipy
  - conda install numpy
  - conda install cython
  - conda install pillow
  - conda install mock
  - conda install nose
  - if [[ "$TRAVIS_PYTHON_VERSION" == 2* ]]; then
      conda install owslib;
    fi
  - conda install pep8
  - conda install proj4
  - conda install pyshp
  - conda install shapely
  - conda install six
  - conda install requests
  - conda install pyepsg

  # Conda debug
  # -----------
  - conda list

  - MPL_CONFIG_DIR=~/.config/matplotlib
  - mkdir -p $MPL_CONFIG_DIR
  - echo "backend" ":" "agg" > $MPL_CONFIG_DIR/matplotlibrc

  # Install cartopy
  # ---------------
  - pip install pyproj
  - pip install cartopy

  # Fetching the IBCAO (if not cached)
  - mkdir -p ibcao_download
  - if [ ! -f ibcao_download/IBCAO_V3_500m_RR.grd ]; then
    wget http://www.ngdc.noaa.gov/mgg/bathymetry/arctic/grids/version3_0/IBCAO_V3_500m_RR.grd -O ibcao_download/IBCAO_V3_500m_RR.grd;
    fi
  - ln -s ibcao_download/IBCAO_V3_500m_RR.grd .

  # Don't plot unnecessary stuff
  - export TRAVIS=1

script:
  - tests/runtests.sh -f test_proj
  - tests/runtests.sh -f test_depth
  - tests/runtests.sh -f test_depth_map
  - tests/runtests.sh -f test_depth_interp.IbcaoDepthTest.test_map_coordinates
  - tests/runtests.sh -f test_depth_interp.IbcaoDepthTest.test_rect_bivariate_spline
  - tests/runtests.sh -f test_depth_map_depth_interp
  - tests/runtests.sh -f test_plot
  - python ibcao.py

